services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - hypenews-data:/var/lib/postgresql/data
    networks:
      - hypenews-network

volumes:
  hypenews-data:

networks:
  hypenews-network:
    driver: bridge
