services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - hypenews-data:/var/lib/postgresql/data
    networks:
      - hypenews-network

volumes:
  hypenews-data:

networks:
  hypenews-network:
    driver: bridge
